// Mock data for auctions
export const mockAllAuctions = [
  {
    id: "auction-1",
    name: "Premium Organic Apples",
    description: "Fresh, organic apples harvested from sustainable orchards.",
    image: "img/1.jpg",
    category: "fruits",
    currentBid: 1350,
    minBid: 1200,
    bidCount: 8,
    timeLeft: 3 * 60 * 60 * 1000, // 3 hours
    reserveMet: true,
    farmer: {
      id: "farmer-1",
      name: "Green Valley Farms",
      location: "Riverside County",
    },
    quantity: "500 kg",
    quality: "Grade A",
    createdAt: "2023-10-15T10:00:00Z",
  },
  {
    id: "auction-2",
    name: "Fresh Heirloom Tomatoes",
    description: "Colorful mix of heirloom tomato varieties, perfect for restaurants.",
    image: "img/2.jpg",
    category: "vegetables",
    currentBid: 950,
    minBid: 800,
    bidCount: 5,
    timeLeft: 8 * 60 * 60 * 1000, // 8 hours
    reserveMet: true,
    farmer: {
      id: "farmer-2",
      name: "Sunshine Organics",
      location: "Central Valley",
    },
    quantity: "300 kg",
    quality: "Organic",
    createdAt: "2023-10-16T09:30:00Z",
  },
  {
    id: "auction-3",
    name: "Premium Grass-Fed Beef",
    description: "Ethically raised, grass-fed beef from free-range cattle.",
    image: "img/3.jpg",
    category: "meat",
    currentBid: 3200,
    minBid: 3000,
    bidCount: 12,
    timeLeft: 1 * 24 * 60 * 60 * 1000, // 1 day
    reserveMet: false,
    farmer: {
      id: "farmer-3",
      name: "Highland Ranch",
      location: "Northern Hills",
    },
    quantity: "200 kg",
    quality: "Premium",
    createdAt: "2023-10-14T14:15:00Z",
  },
  {
    id: "auction-4",
    name: "Artisanal Goat Cheese",
    description: "Small-batch goat cheese made with traditional methods.",
    image: "img/4.jpg",
    category: "dairy",
    currentBid: 850,
    minBid: 700,
    bidCount: 7,
    timeLeft: 2 * 24 * 60 * 60 * 1000, // 2 days
    reserveMet: true,
    farmer: {
      id: "farmer-4",
      name: "Mountain Dairy",
      location: "Alpine Region",
    },
    quantity: "50 kg",
    quality: "Artisanal",
    createdAt: "2023-10-17T11:45:00Z",
  },
  {
    id: "auction-5",
    name: "Organic Quinoa",
    description: "Sustainably grown organic quinoa, high in protein and nutrients.",
    image: "img/3.jpg",
    category: "grains",
    currentBid: 1800,
    minBid: 1500,
    bidCount: 9,
    timeLeft: 4 * 24 * 60 * 60 * 1000, // 4 days
    reserveMet: true,
    farmer: {
      id: "farmer-5",
      name: "Fertile Fields",
      location: "Eastern Plains",
    },
    quantity: "1000 kg",
    quality: "Certified Organic",
    createdAt: "2023-10-13T08:20:00Z",
  },
  {
    id: "auction-6",
    name: "Fresh Honey Collection",
    description: "Variety of raw, unfiltered honey from wildflower meadows.",
    image: "img/2.jpg",
    category: "other",
    currentBid: 1100,
    minBid: 900,
    bidCount: 14,
    timeLeft: 6 * 60 * 60 * 1000, // 6 hours
    reserveMet: true,
    farmer: {
      id: "farmer-6",
      name: "Buzzing Meadows",
      location: "Flower Valley",
    },
    quantity: "100 kg",
    quality: "Raw & Unfiltered",
    createdAt: "2023-10-16T15:30:00Z",
  },
]

// Mock data for the user's own auctions
export const mockMyAuctions = [
  {
    id: "my-auction-1",
    name: "Premium Organic Strawberries",
    description: "Sweet, juicy strawberries grown without pesticides.",
    image: "img/1.jpg",
    category: "fruits",
    currentBid: 1050,
    minBid: 900,
    bidCount: 6,
    timeLeft: 12 * 60 * 60 * 1000, // 12 hours
    reserveMet: true,
    farmer: {
      id: "current-user",
      name: "Your Farm",
      location: "Your Location",
    },
    quantity: "200 kg",
    quality: "Organic",
    createdAt: "2023-10-15T16:45:00Z",
  },
  {
    id: "my-auction-2",
    name: "Fresh Herbs Assortment",
    description: "Variety pack of fresh culinary herbs for restaurants.",
    image: "img/2.jpg",
    category: "herbs",
    currentBid: 750,
    minBid: 600,
    bidCount: 4,
    timeLeft: 2 * 24 * 60 * 60 * 1000, // 2 days
    reserveMet: false,
    farmer: {
      id: "current-user",
      name: "Your Farm",
      location: "Your Location",
    },
    quantity: "50 kg",
    quality: "Premium",
    createdAt: "2023-10-16T10:30:00Z",
  },
  {
    id: "my-auction-3",
    name: "Organic Free-Range Eggs",
    description: "Farm-fresh eggs from free-range, organically fed chickens.",
    image: "img/3.jpg",
    category: "other",
    currentBid: 450,
    minBid: 350,
    bidCount: 8,
    timeLeft: 1 * 24 * 60 * 60 * 1000, // 1 day
    reserveMet: true,
    farmer: {
      id: "current-user",
      name: "Your Farm",
      location: "Your Location",
    },
    quantity: "500 dozen",
    quality: "Organic",
    createdAt: "2023-10-17T09:15:00Z",
  },
];

